# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.CONFIG_MAP_NAME }}
  namespace: default
data:
  HUGGINGFACEHUB_API_TOKEN: {{ .Values.HUGGINGFACEHUB_API_TOKEN }}
  LLM_MODEL_ID: {{ .Values.config.LLM_MODEL_ID }}
  NODE_SELECTOR: {{ .Values.config.NODE_SELECTOR }}
  TGI_LLM_ENDPOINT: http://faq-tgi-svc.default.svc.cluster.local:8010

  ASR_ENDPOINT: http://whisper-svc.default.svc.cluster.local:7066
  TTS_ENDPOINT: http://speecht5-svc.default.svc.cluster.local:7055
  TGI_LLM_ENDPOINT: http://llm-dependency-svc.default.svc.cluster.local:3006
  MEGA_SERVICE_HOST_IP: audioqna-backend-server-svc
  ASR_SERVICE_HOST_IP: asr-svc
  ASR_SERVICE_PORT: "3001"
  LLM_SERVICE_HOST_IP: llm-svc
  LLM_SERVICE_PORT: "3007"
  TTS_SERVICE_HOST_IP: tts-svc
  TTS_SERVICE_PORT: "3002"
---
