{{- range $deployment := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployment.name }}
  namespace: default
spec:
  replicas: {{ $deployment.spec.replicas }}
  selector:
    matchLabels:
      app: {{ $deployment.name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: 'true'
      labels:
        app: {{ $deployment.name }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: qna-config
        {{- if $deployment.spec.args }}
        args:
        {{- range $arg := $deployment.spec.args }}
          - {{ $arg.name }}
          {{- if $arg.value }}
          - {{ $arg.value }}
          {{- end }}
        {{- end }}
        {{- end }}

        {{- if $deployment.spec.env }}
        env:
        {{- range $env := $deployment.spec.env }}
          - name: {{ $env.name }}
            value: {{ $env.value }}
        {{- end }}
        {{- end }}

        image: {{ $deployment.spec.image_name }}:{{ $deployment.spec.image_tag }}
        imagePullPolicy: IfNotPresent
        name: {{ $deployment.name }}

        {{- if $deployment.spec.ports }}
        ports:
        {{- range $port := $deployment.spec.ports }}
          - containerPort: {{ $port.containerPort }}
        {{- end }}
        {{- end }}

        {{- if $deployment.spec.resources }}
        resources:
        {{- range $resourceType, $resource := $deployment.spec.resources }}
          {{ $resourceType }}:
          {{- range $limitType, $limit := $resource }}
            {{ $limitType }}: {{ $limit }}
          {{- end }}
        {{- end }}
        {{- end }}
      hostIPC: true
      nodeSelector:
        node-type: chatqna-opea
      serviceAccountName: default
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: {{ $deployment.name }}
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
---
{{- end }}
